name: auto-format-on-push

on:
  push:
    branches:
      - master

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Clang-Format
        run: sudo apt-get install -y clang-format

      - name: Format Code
        run: find src -name "*.hpp" -o -name "*.cpp" | xargs clang-format -i

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action auto-format-on-push"
          git commit -am "Refactor : Auto format code"
          git push
